/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Graph.LAGraph;
/**
 *
 * @author user
 */
public class Insertar extends javax.swing.JFrame {
static LAGraph grafo;
    /**
     * Creates new form Insertar
     */
    public Insertar(LAGraph g) {
        this.grafo = g;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoInsertar = new javax.swing.JTextField();
        BotonInsertar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextoCrear1 = new javax.swing.JTextField();
        TextoCrear2 = new javax.swing.JTextField();
        Distancia = new javax.swing.JTextField();
        Unir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Insertar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese el numero de la ciudad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        TextoInsertar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(TextoInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, -1));

        BotonInsertar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonInsertar1.setText("Insertar");
        jPanel1.add(BotonInsertar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Ingrese dos ciudades para crear un camino y la distancia entre ellas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        TextoCrear1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCrear1ActionPerformed(evt);
            }
        });
        jPanel1.add(TextoCrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, -1));

        TextoCrear2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCrear2ActionPerformed(evt);
            }
        });
        jPanel1.add(TextoCrear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 190, -1));

        Distancia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanciaActionPerformed(evt);
            }
        });
        jPanel1.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 140, -1));

        Unir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Unir.setText("Unir");
        Unir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnirActionPerformed(evt);
            }
        });
        jPanel1.add(Unir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCrear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCrear1ActionPerformed

    private void TextoCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCrear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCrear2ActionPerformed

    private void DistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaActionPerformed

    private void UnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnirActionPerformed
        // TODO add your handling code here:
        this.grafo.insertEdge(Integer.parseInt(this.TextoCrear1.getText()), Integer.parseInt(this.TextoCrear2.getText()), Integer.parseInt(this.Distancia.getText()));
    }//GEN-LAST:event_UnirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertar(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInsertar1;
    private javax.swing.JTextField Distancia;
    private javax.swing.JTextField TextoCrear1;
    private javax.swing.JTextField TextoCrear2;
    private javax.swing.JTextField TextoInsertar;
    private javax.swing.JButton Unir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
